// auth/app/auth/signup/page.tsx
'use client'

import { handleSignUpForm } from '@/app/actions/auth';
import Link from 'next/link';
import React from 'react'

export default function Signup() {
    const { handleSubmit, errors } = handleSignUpForm()
    return (
        <main className="h-[calc(100vh-10vh)] flex items-center justify-center">
            <div className="w-[400px] mx-auto px-5 xl:px-0">
                <div className="bg-white shadow-lg border px-6 py-10 rounded-lg">
                    <h1 className="text-[1.4rem] text-center font-[500] mb-10">Sign Up</h1>
                    <form onSubmit={handleSubmit} className="space-y-8">
                        <div>
                            <input type="text" name="name" placeholder="Name" className="form-input" />
                            {errors?.name && <p className="form-error">{errors.name}</p>}
                        </div>
                        <div>
                            <input type="email" name="email" placeholder="Email" className="form-input" />
                            {errors?.email && <p className="form-error">{errors.email}</p>}
                        </div>
                        <div>
                            <input type="text" name="password" placeholder="Password" className="form-input" />
                            {errors?.password && <p className="form-error">{errors.password}</p>}
                        </div>

                        <div className="pt-10">
                            <button type="submit" className="w-full bg-blue-800 text-white font-[500] text-[0.9rem] py-1 rounded-sm">Sign up</button>
                        </div>
                    </form>
                    <div className="mt-4 flex flex-row items-center justify-center gap-[5px]">
                        <span className="text-[0.8rem] text-gray-400">Already have an account?</span>
                        <Link href='/auth/login' className="underline text-blue-800 text-[0.95rem] font-[500]">Login</Link></div>
                </div>
            </div>
        </main>
    )
}

// products-js/src/routes/sign_up/+page.svelte
<script>
    import { validateUser, userData, error } from "$lib/store/createUserStore";
</script>

<section class="py-[5rem]">
    <div class="max-w-[500px] mx-auto px-5 xl:px-0">
        {#if $error}
            <div
                class="my-2 py-3 px-3 w-full bg-slate-600 rounded-md text-white"
            >
                {$error}
            </div>
        {/if}
        <form
            on:submit|preventDefault={validateUser}
            class="bg-slate-800 rounded-lg px-8 py-8 space-y-2"
        >
            <input
                type="text"
                placeholder="Name"
                class="bg-input px-3 py-2"
                bind:value={$userData.name}
            />
            <input
                type="email"
                placeholder="Email"
                class="bg-input px-3 py-2"
                bind:value={$userData.email}
            />
            <input
                type="password"
                placeholder="Password"
                class="
            bg-input px-3 py-2"
                bind:value={$userData.password}
            />
            <input
                type="password"
                placeholder="Confirm Password"
                class="bg-input px-3 py-2"
                bind:value={$userData.confirmPassword}
            />
            <div class="pt-5 flex justify-center">
                <button type="submit" class="form-button"> Sign Up </button>
            </div>
        </form>
    </div>
</section>
