// products-js/src/lib/components/Navbar.svelte
<script>
    import { goto } from "$app/navigation";
    import NavLink from "./NavLink.svelte";
</script>

<nav class="bg-navbar h-[10vh]">
    <div class="max-w-responsive h-full">
        <div class="flex flex-row items-center justify-between h-full">
            <h1 class="text-[1.2rem] uppercase font-bold text-white">
                Products App
            </h1>
            <ul
                class="flex flex-row items-center gap-8 uppercase text-[0.9rem] font-[500] tracking-wide"
            >
                <NavLink href="/" text="Home" />
                <NavLink href="/create" text="Create" />
                <div class="space-x-1">
                    <button on:click={() => goto("/sign_up")} class="nav-button"
                        >Sign Up</button
                    >
                    <button on:click={() => goto("/login")} class="nav-button"
                        >Login</button
                    >
                </div>
            </ul>
        </div>
    </div>
</nav>

// auth-pro/components/navbar.tsx
import Link from 'next/link'
import React from 'react'

export const Navbar = () => {
    return (
        <nav className='h-[10vh] bg-black w-full py-2'>
            <div className="max-w-responsive h-full">
                <div className="flex flex-row items-center justify-between h-full">
                    <Link href="/" className='text-white font-bold uppercase'>NextAuth</Link>
                    <div className="space-x-2">
                        {
                            <Link href='/login' className='bg-white rounded-md px-5 py-2 text-black'>Login</Link>
                        }
                    </div>
                </div>
            </div>
        </nav>
    )
}
