// products-js/src/routes/login/+page.svelte
<script>
    import { user, error, validateUser } from "$lib/store/loginUserStore";
</script>

<section class="py-[5rem]">
    <div class="max-w-[500px] mx-auto px-5 xl:px-0">
        {#if $error}
            <div
                class="my-2 py-3 px-3 w-full bg-slate-600 rounded-md text-white"
            >
                {$error}
            </div>
        {/if}
        <form
            on:submit={validateUser}
            class="bg-slate-800 rounded-lg px-8 py-8 space-y-2"
        >
            <input
                type="email"
                placeholder="Email"
                class="bg-input px-3 py-2"
                bind:value={$user.email}
            />
            <input
                type="password"
                placeholder="Password"
                class="
            bg-input px-3 py-2"
                bind:value={$user.password}
            />
            <div class="pt-5 flex justify-center">
                <button type="submit" class="form-button"> Login </button>
            </div>
        </form>
    </div>
</section>

// user-upload/app/auth/login/page.tsx
import Link from 'next/link'
import React from 'react'

export default function Login() {
  return (
      <main className="h-[calc(100vh-10vh)] flex items-center justify-center">
          <div className="w-[400px] mx-auto px-5 xl:px-0">
              <div className="bg-white shadow-lg border px-6 py-10 rounded-lg">
                  <h1 className="text-[1.4rem] text-center font-[500] mb-10">Login</h1>
                  <form  className="space-y-8">
                      <div>
                          <input type="email" name="email" placeholder="Email" className="form-input" />
                      </div>
                      <div>
                          <input type="text" name="password" placeholder="Password" className="form-input" />
                      </div>

                      <div className="pt-10">
                          <button type='submit' className="w-full bg-slate-800 text-white font-[500] text-[0.9rem] py-1 rounded-sm">{'Login'}</button>
                      </div>
                  </form>
                  <div className="mt-4 flex flex-row items-center justify-center gap-[5px]">
                      <span className="text-[0.8rem] text-gray-400">{"Don't have an account?"}</span>
                      <Link href='/auth/signup' className="underline text-slate-800 text-[0.95rem] font-[500]">Sign up</Link></div>
              </div>
          </div>
      </main>
  )
}
