// datas/app/(root)/[id]/page.tsx
'use client'

import { deleteProductAction } from '@/app/actions/deleteProduct'
import { getProductAction } from '@/app/actions/getProducts'
import { Product } from '@/app/interfaces/productInterface'
import Link from 'next/link'
import { usePathname, useRouter } from 'next/navigation'
import React, { useEffect, useState } from 'react'

export default function ProductDetails() {
    const pathName = usePathname()
    const router = useRouter()
    const [product, setProduct] = useState<Product | undefined>()

    const fetchProduct = async () => {
        try {
            const productDetails = await getProductAction(pathName);
            setProduct(productDetails)
        } catch (error) {
            console.log(`Error fetching product: ${error}`)
        }
    }

    const handleDeleteProduct = async () => {
        try {
            const result = await deleteProductAction(pathName);
            console.log(result);
            router.push('/')
        } catch (error) {
            console.log(`Error deleting product: ${error}`)
        }
    }

    useEffect(() => {
        fetchProduct()
    }, [pathName])
    return (
        <section className='py-[5rem]'>
            {
                product ? <div className="max-w-[600px] mx-auto px-5 xl:px-0">
                    <div className="px-6 py-8 border-4 border-green-300 bg-green-50 rounded-md">
                        <div className="bg-green-300 text-white px-4 py-4 rounded-md">
                            <h2 className='text-[1.5rem] font-bold'>{product.name}</h2>
                            <h3 className='text-[1.2rem] font-[500]'>{product.brand}</h3>
                            <p className='text-[1.5rem] text-bold'>${product.price}</p>
                            <p>{product.description}</p>
                        </div>
                        <div className="pt-4 flex flex-row items-center justify-center md:justify-end gap-[10px]">
                            <Link href={`/add?id=${product._id}`} className='border-2 border-blue-500 rounded-md px-[30px] py-1 bg-blue-50 text-blue-500 uppercase text-[0.9rem] transition-all duration-300 hover:bg-blue-500 hover:text-white'>Edit</Link>
                            <button onClick={handleDeleteProduct} className='border-2 border-red-500 rounded-md px-[30px] py-1 bg-red-50 text-red-500 uppercase text-[0.9rem] transition-all duration-300 hover:bg-red-500 hover:text-white'>Delete</button>
                        </div>
                    </div>
                </div> : null
            }
        </section>
    )
}

// my-app/src/routes/[id]/+page.svelte
<script lang="ts">
    import { goto } from "$app/navigation";
    import { page } from "$app/stores";
    import { onMount } from "svelte";

    let product: Product | null = null;

    const deleteProduct = async (productId: string) => {
        try {
            const response = await fetch(`/api/products/${productId}`, {
                method: "DELETE",
            });
            if (!response.ok) {
                console.error("Error: ", response.json());
            }
            console.log("Product deleted");
            goto("/");
        } catch (error) {
            console.error("Failed to delete product");
        }
    };

    const fetchProduct = async () => {
        let productId = $page.params.id;

        try {
            const response = await fetch(`/api/products/${productId}`);
            if (!response.ok) {
                throw new Error("Product not found");
            }
            const data = await response.json();
            product = data;
        } catch (error) {
            console.error("Failed fetch product", error);
        }
    };

    onMount(() => {
        fetchProduct();
    });
</script>

<section class="py-[5rem]">
    <div class="max-w-[600px] mx-auto px-5 xl:px-0">
        {#if product}
            <div class="bg-black text-white px-8 py-8 rounded-md space-y-1">
                <h1 class="text-[1.5rem] font-bold">{product.name}</h1>
                <h2 class="text-[1.2rem] font-[500]">{product.brand}</h2>
                <p class="text-[1.5rem] font-bold">${product.price}</p>
                <p class="">{product.description}</p>
                <div
                    class="pt-[5rem] flex flex-row items-center justify-end gap-[10px]"
                >
                    <button
                        class="border border-white text-white rounded-md px-5 py-2 transition-all duration-300 hover:bg-white hover:text-black"
                        >Update</button
                    >
                    <button
                        on:click={() => product && deleteProduct(product._id)}
                        class="border border-white text-white rounded-md px-5 py-2 transition-all duration-300 hover:bg-white hover:text-black"
                        >Delete</button
                    >
                </div>
            </div>
        {/if}
    </div>
</section>
