// products-js/src/routes/sign_up/+page.svelte
<section class="py-[5rem]">
    <div class="max-w-[500px] mx-auto px-5 xl:px-0">
        <form action="" class="bg-slate-800 rounded-lg px-8 py-8 space-y-2">
            <input type="text" placeholder="Name" class="bg-input px-3 py-2" />
            <input
                type="email"
                placeholder="Email"
                class="bg-input px-3 py-2"
            />
            <input
                type="password"
                placeholder="Password"
                class="
            bg-input px-3 py-2"
            />
            <input
                type="password"
                placeholder="Confirm Password"
                class="bg-input px-3 py-2"
            />
            <div class="pt-5 flex justify-center">
                <button type="submit" class="form-button"> Sign Up </button>
            </div>
        </form>
    </div>
</section>

// auth-pro/app/(auth)/signup/page.tsx
import React from 'react'
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import Link from "next/link";

export default function Signup() {
    return (
        <main className='py-[5rem]'>
            <div className="max-w-responsive">
                <Card className='w-[400px] mx-auto'>
                    <CardHeader>
                        <CardTitle className='text-center'>Signup</CardTitle>
                    </CardHeader>
                    <CardContent className="mt-8">
                        <form className="space-y-2">
                            <div>
                                <input type="name" name="name" placeholder="Name" className="form-input" />
                            </div>
                            <div>
                                <input type="email" name="email" placeholder="Email" className="form-input" />
                            </div>
                            <div>
                                <input type="text" name="password" placeholder="Password" className="form-input" />
                            </div>
                            <div className="pt-10">
                                <button type="submit" className="w-full bg-slate-800 text-white font-[500] text-[0.9rem] py-2 rounded-sm flex flex-row items-center justify-center gap-[10px]">{'Signup'}</button>
                            </div>
                        </form>
                        <div className="mt-4 flex flex-row items-center justify-center gap-[5px]">
                            <span className="text-[0.8rem] text-gray-400">{"Don't have an account?"}</span>
                            <Link href='/login' className="underline text-slate-800 text-[0.95rem] font-[500]">Login</Link></div>
                    </CardContent>
                </Card>
            </div>
        </main>
    )
}
