// fetch-products/src/lib/components/Navbar.svelte
<nav class="bg-indigo-950 h-[10vh] w-full">
	<div class="max-w-responsive h-full">
		<div class="h-full flex flex-row items-center justify-between">
			<h1 class="text-white text-[1.2rem] font-bold uppercase">Ecom</h1>
			<ul>
				<li class="relative">
					<a href="/cart" class="text-white">
						<i class="fa-solid fa-cart-shopping mr-2"></i>
						<span
							class="absolute top-[-8px] right-[-5px] bg-red-500 rounded-[50%] text-bold text-[0.6rem] min-h-[15px] min-w-[15px] px-1 text-center"
							>1</span
						>
					</a>
				</li>
			</ul>
		</div>
	</div>
</nav>

// user-upload/components/navbar.tsx
import Link from 'next/link'
import React from 'react'

export default function Navbar() {
    return (
        <nav className='h-[10vh] bg-black w-full py-2'>
            <div className="max-w-responsive h-full">
                <div className="flex flex-row items-center justify-between h-full">
                    <Link href="/" className='text-white font-bold uppercase'>My Users</Link>
                    <Link href='/users/add' className='bg-white rounded-md px-5 py-2 text-black'>Add Users</Link>
                </div>
            </div>
        </nav>
    )
}
